<h2 style="color:green" align="center"> Machine Learning With Python: Linear Regression Multiple Variables</h2>

<h3 style="color:purple">Sample problem of predicting home price in monroe, new jersey (USA)</h3>

Below is the table containing home prices in monroe twp, NJ. Here price depends on **area (square feet), bed rooms and age of the home (in years)**. Given these prices we have to predict prices of new homes based on area, bed rooms and age.

<img src="homeprices.jpg" style='height:200px;width:350px'>

Given these home prices find out price of a home that has,

**3000 sqr ft area, 3 bedrooms, 40 year old**

**2500 sqr ft area, 4 bedrooms,  5 year old**

We will use regression with multiple variables here. Price can be calculated using following equation,

<img src="equation.jpg" >

Here area, bedrooms, age are called independant variables or **features** whereas price is a dependant variable

In [14]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [15]:
df = pd.read_excel(r"C:\Users\lom\Desktop\expenditure1.xlsx")
df

Expenditure  Bank Charges  Conveyance (Maint)  Depreciation  DTH Charges  \
0       year1          2837                   0     659240.00        85603   
1       year2           266               20250     791534.49        66872   
2       year3           236               12500     747291.99        91004   
3       year4          4432               19590     691168.10        87341   

   Electrical Repair  General Repair  Gift Expenses (Maint)  \
0             215841          718357                      0   
1             125925          203113                  36616   
2             115751          104718                      0   
3             231962          111870                      0   

   Guest expenses (Maint)  Hiring Labour Charges  ...  Party decoration  \
0                       0                      0  ...                 0   
1                  100000                 128960  ...                 0   
2                       0                  23500  ...              8500   
3                       0                   1500  ...                 0   

   Maintenance  Miscellaneous  Diesel for OMQ  Electrical purchase  \
0            0         177854           27641                31073   
1            0           1508               0                    0   
2       178659              0               0                    0   
3       330136              0               0                    0   

   Rent and Allied charges O/S  WOC property items  Balance C/F       Total  \
0                        22188            45173.00       438023  3829571.00   
1                            0           223674.29       384052  3480395.00   
2                            0           237585.49            0  3144106.48   
3                            0            97319.26            0  2855557.36   

   Growth  
0    9.27  
1    5.11  
2    1.99  
3    1.16  

[4 rows x 37 columns]

**Data Preprocessing: Fill NA values with median value of a column**

df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

In [16]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('Growth',axis='columns'),df.Growth)

ValueError: could not convert string to float: 'year1'

In [7]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [8]:
reg.intercept_

221323.00186540408

**Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old**

In [9]:
reg.predict([[3000, 3, 40]])

array([498408.25158031])

In [10]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540384

498408.25157402386

**Find price of home with 2500 sqr ft area, 4 bedrooms,  5 year old**

In [11]:
reg.predict([[2500, 4, 5]])

array([578876.03748933])

<h3>Exercise<h3>

In exercise folder (same level as this notebook on github) there is **hiring.csv**. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,


**2 yr experience, 9 test score, 6 interview score**

**12 yr experience, 10 test score, 10 interview score**


<h3>Answer<h3>

53713.86 and 93747.79